# Generated by Django 2.2.4 on 2021-06-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0002_auto_20210622_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sended_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='user_dashboard_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_commited', to='user_dashboard_app.User'),
        ),
    ]
